name: build

on:
  push:
  workflow_dispatch:

# Indicate that we are running in CI
env:
  WM_CI_BUILD: true

jobs:
  build-uefi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Project-Aloha/mu_aloha_platforms
          ref: main
          path: MU
      - name: Build UEFI
        run: |
          cd MU
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git submodule update --init --recursive
          sed -i '/"Kernel"/s/Conv/Reserv/' Platforms/SurfaceDuo1Pkg/Device/xiaomi-nabu/Library/PlatformMemoryMapLib/PlatformMemoryMapLib.c
          sed -i 's/levenshtein/python-Levenshtein/' pip-requirements.txt
          sed -i 's/edk2-pytool-library==0.22.5/edk2-pytool-library>=0.23.0/' pip-requirements.txt
          sed -i 's/edk2-pytool-extensions==0.28.0/edk2-pytool-extensions>=0.29.0/' pip-requirements.txt
          bash scripts/ci_setup.sh && ./build_uefi.py -d xiaomi-nabu
          find Build/*/ci_artifacts/xiaomi_nabu/ -type f -name 'SM8150_EFI_SB.fd' -exec cp '{}' ../SM8150_EFI_SB.fd ';'
          find Build/*/ci_artifacts/xiaomi_nabu/ -type f -name 'xiaomi-nabu_SB.img' -exec cp '{}' ../xiaomi-nabu_SB.img ';'
          find Build/*/ci_artifacts/xiaomi_nabu/ -type f -name 'SM8150_EFI_NOSB.fd' -exec cp '{}' ../SM8150_EFI_NOSB.fd ';'
          find Build/*/ci_artifacts/xiaomi_nabu/ -type f -name 'xiaomi-nabu_NOSB.img' -exec cp '{}' ../xiaomi-nabu_NOSB.img ';'
      - uses: actions/upload-artifact@v4
        with:
          name: SM8150_EFI_SB.fd
          path: |
            SM8150_EFI_SB.fd
      - uses: actions/upload-artifact@v4
        with:
          name: xiaomi-nabu_SB.img
          path: |
            xiaomi-nabu_SB.img
      - uses: actions/upload-artifact@v4
        with:
          name: SM8150_EFI_NOSB.fd
          path: |
            SM8150_EFI_NOSB.fd
      - uses: actions/upload-artifact@v4
        with:
          name: xiaomi-nabu_NOSB.img
          path: |
            xiaomi-nabu_NOSB.img
  build-dbkp:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: rodriguezst/DualBootKernelPatcher
          ref: PStore
          path: DBKP
      - name: Build DBKP & Shellcodes
        run: |
          pushd DBKP
          cmake -B ./Build -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
          cmake --build ./Build --config Release --target all
          popd
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DualBootKernelPatcher
          path: |
            DBKP/Build/DualBootKernelPatcher
            DBKP/Build/DualBootKernelRemover
            DBKP/Build/ShellCode/*.bin
            DBKP/Config/*.cfg
  build-installer:
    needs: [build-uefi, build-dbkp]
    strategy:
      matrix:
        uefi-type: [SB, NOSB]
        dualboot-type: [case, bootmanager]
    runs-on: ubuntu-latest
    steps:
      - id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYYMMDD'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@v4
        with:
          name: SM8150_EFI_${{ matrix.uefi-type }}.fd
      - uses: actions/download-artifact@v4
        with:
          name: DualBootKernelPatcher
          path: DBKP
      - name: Build Zip Installer (${{ matrix.uefi-type }})
        shell: bash
        run: |
          if [[ "${{ matrix.dualboot-type }}" == "bootmanager" ]]; then
            SHELLCODE="PStore"
          fi
          mv SM8150_EFI_${{ matrix.uefi-type }}.fd Flashable_UEFI_Installer/SM8150_EFI.fd
          mv DBKP/Build/DualBootKernelPatcher Flashable_UEFI_Installer/DualBootKernelPatcher
          chmod +x Flashable_UEFI_Installer/DualBootKernelPatcher
          mv DBKP/Build/ShellCode/ShellCode.Nabu${SHELLCODE}.bin Flashable_UEFI_Installer/ShellCode.Nabu${SHELLCODE}.bin
          mv DBKP/Config/DualBoot.Sm8150.cfg Flashable_UEFI_Installer/DualBoot.Sm8150.cfg
          cd Flashable_UEFI_Installer
          ./pack.sh
          mv installer.zip installer_${{ matrix.dualboot-type }}_${{ matrix.uefi-type }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: installer_${{ matrix.dualboot-type }}_${{ matrix.uefi-type }}.zip
          path: |
            Flashable_UEFI_Installer/installer_${{ matrix.dualboot-type }}_${{ matrix.uefi-type }}.zip
      - name: Release assets
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          target_commitish: ${{ github.sha }}
          name: DualBoot UEFI Installer (${{ steps.time.outputs.time }})
          body_path: README.md
          draft: false
          prerelease: false
          files: |
            Flashable_UEFI_Installer/installer_${{ matrix.dualboot-type }}_${{ matrix.uefi-type }}.zip

